name: http_throttle
version: 1.0.0
description: HTTP client middleware that throttles requests.
dependencies:
  http: ">=0.9.0 <0.12.0"
  pool: ">=1.0.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
