name: stack_trace

# Note! This version number is referenced directly in the pub source code in
# lib/src/barback.dart. Pub implicitly places a version constraint on
# stack_trace to ensure users only select a version of stack_trace that works
# with their current version of pub.
#
# When the major version is upgraded, you *must* update that version constraint
# in pub to stay in sync with this.
version: 1.1.1
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A package for manipulating stack traces and printing them readably.

dependencies:
  path: ">=1.2.0 <2.0.0"

dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"
environment:
  sdk: ">=1.7.0-dev.4.0 <2.0.0"
