name: coverage_browser
version: 0.1.0-dev
description: Code coverage browser
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  petitparser: any
  polymer: any
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
transformers:
- polymer:
    entry_points: web/index.html
