name: args
version: 0.12.1-dev
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
 Library for defining parsers for parsing raw command-line arguments into
 a set of options and values using GNU and POSIX style options.

dependencies:
  collection: ">=0.9.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.11.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
