name: http_multi_server
version: 1.3.0+1
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description:
  A dart:io HttpServer wrapper that handles requests from multiple servers.
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
  http: ">=0.11.0 <0.12.0"
environment:
  sdk: ">=1.7.0-edge.40587 <2.0.0"
