name: source_maps
version: 0.10.0
author: Dart Team <misc@dartlang.org>
description: Library to programmatically manipulate source map files.
homepage: http://www.dartlang.org
dependencies:
  path: '>=1.2.0 <2.0.0'
  source_span: '>=1.0.0 <2.0.0'
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
